### ISSUE TITLE
Allow installing with plugin managers

### ISSUE THREAD

**Issue by weirdan** [TysonAndre/vim-syntax#7]
Are you open to accepting a PR to make this repo a vim plugin, so that it could be installed and updated with plugin managers?

The reason I ask is that neovim ships outdated syntax file, and the syntax file I used to use (as a vim plugin) is no longer supported. So I'd like to use yours on neovim, as a plugin.

**Comment by TysonAndre** [comment]
What steps would that involve for neovim? Moving it to syntax/php.vim? Anything else?

**Comment by weirdan** [comment]
That, and (optionally) renaming the repo. Plugin managers usually clone the repo and keep the name - so if the repo name is kept as is, it would be referred to as `TysonAndre/vim-syntax` and installed into `$PLUGIN_DIR/vim-syntax` - both are not very descriptive.

Something like `TysonAndre/vim-php-syntax` would be much clearer.

**Comment by TysonAndre** [comment]
I've done the following - let me know if anything else should be done

1. Renamed the repo to php-vim-syntax
2. Moved this to syntax/php.vim
3. Added a README mentioning that this can be installed, either manually or as a plugin.

**Comment by TysonAndre** [comment]
For the neovim changes, it seems like the process of applying patches are fairly cumbersome for the syntax workflow due to combining unrelated files for runtime updates.

https://github.com/neovim/neovim/issues/12844

There's 3 commits called "Update runtime files" and those contain edits to dozens of files - the most recent updates to neovim's runtime/syntax are just "Port $LANGUAGE syntax file only"

```
» scripts/vim-patch.sh -l runtime/syntax/php.vim 
Cloning Vim into: /path/to/neovim/.vim-src                   
Cloning into '/path/to/.vim-src'...                                                                                                     
remote: Enumerating objects: 28, done.                                                                                                                             
remote: Counting objects: 100% (28/28), done.                                    
remote: Compressing objects: 100% (23/23), done.                                                                                                                   
remote: Total 124816 (delta 8), reused 13 (delta 5), pack-reused 124788       
Receiving objects: 100% (124816/124816), 104.48 MiB | 6.56 MiB/s, done.                                                                                            
Resolving deltas: 100% (105539/105539), done.                                    
Vim patches missing from Neovim:                                                 
  • 5ef1c6a4838a9629b793f3ae676f72a764171b00: Update runtime files               
  • 47e13953ffdbb9f163b901196dec8c2100b72edd: Update runtime files
  • 1c6737b20a5cf71751b180461cea22fc76d8870c: Update runtime files.
```

```
» grep '+++' vim-5ef1c6a4838a.patch 
+++ b/nsis/lang/turkish.nsi
+++ b/runtime/autoload/netrw.vim
+++ b/runtime/autoload/netrw_gitignore.vim
+++ b/runtime/doc/diff.txt
+++ b/runtime/doc/eval.txt
+++ b/runtime/doc/gui.txt
+++ b/runtime/doc/map.txt
+++ b/runtime/doc/motion.txt
+++ b/runtime/doc/options.txt
+++ b/runtime/doc/pi_netrw.txt
+++ b/runtime/doc/quickref.txt
+++ b/runtime/doc/tagsrch.txt
+++ b/runtime/doc/terminal.txt
+++ b/runtime/doc/textprop.txt
+++ b/runtime/doc/visual.txt
+++ b/runtime/lang/menu_tr.iso_8859-9.vim
+++ /dev/null
+++ b/runtime/lang/menu_tr_tr.iso_8859-9.vim
+++ /dev/null
+++ b/runtime/lang/menu_tr_tr.utf-8.vim
+++ b/runtime/menu.vim
+++ b/runtime/optwin.vim
+++ b/runtime/plugin/netrwPlugin.vim
+++ b/runtime/spell/main.aap
+++ b/runtime/spell/tr/main.aap
+++ b/runtime/syntax/erlang.vim
+++ b/runtime/syntax/netrw.vim
+++ b/runtime/syntax/php.vim
+++ b/runtime/syntax/vim.vim
+++ b/runtime/tutor/tutor.tr.iso9
+++ b/runtime/tutor/tutor.tr.utf-8
+++ b/src/nvim/po/tr.po
```

**Comment by TysonAndre** [comment]
I created a PR to update neovim, but I'm not familiar with their standard workflow. This seems to be the method used for updating runtime/syntax/javascript.vim

**Comment by weirdan** [comment]
Works like a charm, thanks!
